# This workflow generates stashes documentation in `docs` branch

name: Generate Docs

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  main:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
        with:
          ref: docs

      - name: Clone master branch
        run: |
          git clone https://github.com/gadhagod/Hyrule-Compendium-node-client

      - name: Install dependencies
        run: |
          cd Hyrule-Compendium-node-client
          npm i
          sudo npm i -g typedoc

      - name: Build documentation
        run: |
          rm -rf docs
          cd Hyrule-Compendium-node-client
          npm run build:docs
          mv docs ../
          cd ..

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit --allow-empty -m "Update docs to version v${{ github.event.release.tag_name }}"

      - name: Push to docs branch
        uses: ad-m/github-push-action@master
        with: 
          branch: docs
          github_token: ${{ secrets.BOT_TOKEN }}